In [7]:
import dataclasses
from numpy.testing import assert_array_equal
import numpy as np
import pandas as pd
import numpy.typing as npt

## Construct array from index arrays

In [8]:
def construct_array(
        matrix: npt.NDArray[np.int_],
        row_indices: npt.NDArray[np.int_] | list[int],
        col_indices: npt.NDArray[np.int_] | list[int]
) -> npt.NDArray[np.int_]:
    """
    Construct slice of given matrix by indices row_indices and col_indices:
    [matrix[row_indices[0], col_indices[0]], ... , matrix[row_indices[N-1], col_indices[N-1]]]
    :param matrix: input matrix
    :param row_indices: list of row indices
    :param col_indices: list of column indices
    :return: matrix slice
    """
    return matrix[row_indices, col_indices]

In [9]:
np.random.seed(10)
A = np.random.randint(1, 100, size=(3, 4))
A

array([[10, 16, 65, 29],
       [90, 94, 30,  9],
       [74,  1, 41, 37]])

In [10]:
construct_array(A, [2, 0, 0], [1, 3, 2])

array([ 1, 29, 65])

In [11]:
construct_array(A, np.arange(3), np.arange(1, 4))

array([16, 30, 37])

In [12]:
# TESTING AREA

@dataclasses.dataclass
class ConstructArrayCase:
    matrix: npt.NDArray[np.int_]
    row_indices: npt.NDArray[np.int_] | list[int]
    col_indices: npt.NDArray[np.int_] | list[int]
    result: npt.NDArray[np.int_]


CONSTRUCT_ARRAY_TEST_CASES = [
    ConstructArrayCase(matrix=np.array(range(25)).reshape(5, 5),
                       row_indices=[0, 1, 2],
                       col_indices=[0, 1, 2],
                       result=np.array([0, 6, 12])),
    ConstructArrayCase(matrix=np.arange(-10, 10).reshape((5, 4)),
                       row_indices=[1, 2, 3, 3],
                       col_indices=[3, 2, 1, 2],
                       result=np.array([-3, 0, 3, 4])),
    ConstructArrayCase(matrix=np.arange(42).reshape((7, 6)),
                       row_indices=[],
                       col_indices=[],
                       result=np.array([])),
    ConstructArrayCase(matrix=np.arange(42).reshape((7, 6)),
                       row_indices=np.arange(4),
                       col_indices=np.arange(4),
                       result=np.array(np.arange(4)) * 7),
    ConstructArrayCase(matrix=np.arange(42).reshape((42, 1)),
                       row_indices=[0, 1, 41],
                       col_indices=[0, 0, 0],
                       result=np.array([0, 1, 41]))
]

for t in CONSTRUCT_ARRAY_TEST_CASES:
    assert_array_equal(construct_array(t.matrix, t.row_indices, t.col_indices), t.result)

## Detect identic arrays

In [29]:
def detect_identic(
        lhs_array: npt.ArrayLike,
        rhs_array: npt.ArrayLike
) -> bool:
    """
    Check whether two arrays are equal or not
    :param lhs_array: first array
    :param rhs_array: second array
    :return: True if input arrays are equal, False otherwise
    """
    return np.array_equal(lhs_array, rhs_array)

In [30]:
detect_identic(5, 5.0)

True

In [31]:
detect_identic('xyz', "xyz")

True

In [32]:
detect_identic([1, 2, 45], [1, 2, 45])

True

In [33]:
detect_identic(np.zeros(10), np.ones(10) - 1)

True

In [34]:
detect_identic([[0, 1], [2, 3]], np.arange(4))

False

In [35]:
detect_identic([[0, 1], [2, 3]], np.arange(4).reshape((2, 2)))

True

In [36]:
# TESTING AREA

@dataclasses.dataclass
class DetectIdenticCase:
    lhs_array: npt.ArrayLike
    rhs_array: npt.ArrayLike
    result: bool


DETECT_IDENTIC_TEST_CASES = [
    DetectIdenticCase(
        lhs_array=np.array([1, 2]),
        rhs_array=np.array([1, 2]),
        result=True),
    DetectIdenticCase(
        lhs_array=np.array([1., 2]),
        rhs_array=np.array([1, 2.]),
        result=True),
    DetectIdenticCase(
        lhs_array=np.array([1, 2]),
        rhs_array=np.array([1.0001, 2]),
        result=False),
    DetectIdenticCase(
        lhs_array=np.array([1, 2]),
        rhs_array=np.array([[1, 2]]),
        result=False),
    DetectIdenticCase(
        lhs_array=np.array([[1, 2, 3]]),
        rhs_array=np.array([[1, 2]]),
        result=False),
    DetectIdenticCase(
        lhs_array=np.array([]),
        rhs_array=np.array([]),
        result=True),
    DetectIdenticCase(
        lhs_array=3,
        rhs_array=3,
        result=True),
    DetectIdenticCase(
        lhs_array=np.array(range(3)),
        rhs_array=np.array(range(3))[np.newaxis, :],
        result=False),
]

for t in DETECT_IDENTIC_TEST_CASES:
    assert_array_equal(detect_identic(t.lhs_array, t.rhs_array), t.result)

## Mean channel

In [50]:
def mean_channel(X: npt.NDArray[np.float_]) -> npt.NDArray[np.float_]:
    """
    Given color image (3-dimensional array of size (n, m, 3).
    Compute average value for all 3 channels
    :param X: color image
    :return: array of size 3 with average values
    """
    return np.mean(X, axis=(0, 1))

In [45]:
A = np.arange(60).reshape(4, 5, 3)

In [49]:
np.mean(A, axis=(0, 1))

array([28.5, 29.5, 30.5])

In [51]:
A = np.arange(48).reshape(4, 4, 3)
mean_channel(A)

array([22.5, 23.5, 24.5])

In [52]:
A = np.random.rand(1920, 1080, 3)
mean_channel(A)

array([0.50007022, 0.50073281, 0.49993379])

In [53]:
# TESTING AREA

@dataclasses.dataclass
class MeanChannelCase:
    X: npt.NDArray[np.float_]
    result: npt.NDArray[np.float_]


MEAN_CHANNEL_TEST_CASES = [
    MeanChannelCase(
        X=np.array(range(5 * 5 * 3)).reshape(5, 5, 3),
        result=np.array([36, 37, 38])),
    MeanChannelCase(
        X=np.dstack((
            (np.arange(320 * 240) % 64).reshape(320, 240),
            (np.arange(320 * 240) % 64).reshape(320, 240) * 2,
            (np.arange(320 * 240) % 64).reshape(320, 240) * 3)),
        result=np.array([31.5, 63., 94.5])),
    MeanChannelCase(
        X=np.array([]).reshape(0, 0, 3),
        result=np.array([np.nan, np.nan, np.nan]))
]

for t in MEAN_CHANNEL_TEST_CASES:
    assert_array_equal(mean_channel(t.X), t.result)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/_methods.py:182: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(


## Unique rows

In [79]:
def get_unique_rows(X: npt.NDArray[np.int_]) -> npt.NDArray[np.int_]:
    """
    Compute unique rows of matrix
    :param X: matrix
    :return: matrix of unique rows
    """
    return np.unique(X, axis=0)

In [72]:
A = np.array([[1, 2], [2, 1], [1, 2]])
A

array([[1, 2],
       [2, 1],
       [1, 2]])

In [73]:
get_unique_rows(A)

array([[1, 2],
       [2, 1],
       [1, 2]])

In [54]:
np.tile([1, 2, 3], 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [55]:
np.repeat([1, 2, 3], 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [74]:
A = np.tile([1, 2, 4, 8], 5).reshape((5, -1))
A

array([[1, 2, 4, 8],
       [1, 2, 4, 8],
       [1, 2, 4, 8],
       [1, 2, 4, 8],
       [1, 2, 4, 8]])

In [75]:
get_unique_rows(A)

array([[1, 2, 4, 8],
       [1, 2, 4, 8],
       [1, 2, 4, 8],
       [1, 2, 4, 8],
       [1, 2, 4, 8]])

In [76]:
A = np.repeat([1, 2, 4, 8], 5).reshape((-1, 5))
A

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4],
       [8, 8, 8, 8, 8]])

In [77]:
get_unique_rows(A)

array([[1],
       [2],
       [4],
       [8]])

In [80]:
# TESTING AREA

@dataclasses.dataclass
class GetUniqueRowsCase:
    X: npt.NDArray[np.int_]
    result: npt.NDArray[np.int_]


GET_UNIQUE_ROWS_TEST_CASES = [
    GetUniqueRowsCase(
        X=np.array([[1, 2, 3]]),
        result=np.array([[1, 2, 3]])),
    GetUniqueRowsCase(
        X=np.array([[4, 5, 6], [0, 1, 2], [1, 2, 3], [0, 1, 2], [4, 5, 6], [1, 2, 3]]),
        result=np.array([[0, 1, 2], [1, 2, 3], [4, 5, 6]])),
]

for t in GET_UNIQUE_ROWS_TEST_CASES:
    assert_array_equal(get_unique_rows(t.X), t.result)

## Construct matrix

In [189]:
def construct_matrix(
        first_array: npt.NDArray[np.int_], second_array: npt.NDArray[np.int_]
) -> npt.NDArray[np.int_]:
    """
    Construct matrix from pair of arrays
    :param first_array: first array
    :param second_array: second array
    :return: constructed matrix
    """

In [188]:
construct_matrix([-1, -2, -3], [10, 20, 30])

array([[-1, 10],
       [-2, 20],
       [-3, 30]])

In [184]:
@dataclasses.dataclass
class ConstructMatrixCase:
    first_array: npt.NDArray[np.int_]
    second_array: npt.NDArray[np.int_]
    result: npt.NDArray[np.int_]


CONSTRUCT_MATRIX_TEST_CASES = [
    ConstructMatrixCase(
        first_array=np.array([1, 2, 3]),
        second_array=np.array([4, 5, 6]),
        result=np.array([[1, 4], [2, 5], [3, 6]])),
    ConstructMatrixCase(
        first_array=np.array([]),
        second_array=np.array([]),
        result=np.array([]).reshape(0, 2)),
    ConstructMatrixCase(
        first_array=np.array([1]),
        second_array=np.array([2]),
        result=np.array([[1, 2]])),
    ConstructMatrixCase(
        first_array=np.arange(0, 100, 2),
        second_array=np.arange(1, 100, 2),
        result=np.arange(100).reshape(50, 2))
]

for t in CONSTRUCT_MATRIX_TEST_CASES:
    assert_array_equal(construct_matrix(t.first_array, t.second_array), t.result)

## Add zeros

In [90]:
import numpy as np
import numpy.typing as npt


def add_zeros(x: npt.NDArray[np.int_]) -> npt.NDArray[np.int_]:
    """
    Add zeros between values of given array
    E.g.: [-1, 3, 5] -> [-1, 0, 3, 0, 5]
    :param x: array,
    :return: array with zeros inserted
    """
    n = len(x)
    if n == 0:
        return np.array([], dtype=int)
    result = np.zeros(2*n - 1, dtype=int)
    result[::2] = x
    return result

In [87]:
add_zeros([-1, 3, 5, 2])

array([-1,  0,  3,  0,  5,  0,  2])

In [88]:
add_zeros([1])

array([1])

In [91]:
add_zeros([])

array([], dtype=int64)

## Max element after 0

In [53]:
def max_element(array: npt.NDArray[np.int_]) -> int | None:
    """
    Return max element after zero for input array.
    If appropriate elements are absent, then return None
    E.g., [6, 2, 0, 3, 0, 0, 5, 7, 0] -> 5
    :param array: array,
    :return: max element value or None
    """

## Nearest value

In [109]:
def nearest_value(matrix: npt.NDArray[np.float_], value: float) -> float | None:
    """
    Find nearest value in matrix.
    If matrix is empty return None
    E.g., matrix = np.arange(0,10).reshape((2, 5)) and value = 3.6 give 4
    :param matrix: input matrix
    :param value: value to find
    :return: nearest value in matrix or None
    """
    if matrix.size == 0:
        return None
    return matrix.ravel()[np.argmin(np.abs(matrix - value))]

In [110]:
matrix = np.arange(0,10).reshape((2, 5))
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [113]:
nearest_value(matrix, 12.3)

9

In [93]:
matrix.size

10

In [97]:
np.abs(matrix - 3.6)

array([[3.6, 2.6, 1.6, 0.6, 0.4],
       [1.4, 2.4, 3.4, 4.4, 5.4]])

In [98]:
np.min(np.abs(matrix - 3.6))

0.3999999999999999

In [99]:
np.argmin(np.abs(matrix - 3.6))

4

In [100]:
B = np.random.rand(2, 5)
B

array([[0.4182803 , 0.90114094, 0.68363347, 0.28737984, 0.97927751],
       [0.43466453, 0.77360153, 0.89142257, 0.26800294, 0.33989471]])

In [103]:
np.argmin(B, axis=1)

array([3, 3])

## Nonzero value

In [126]:
def nonzero_product(matrix: npt.NDArray[np.int_]) -> int | None:
    """
    Compute product of nonzero diagonal elements of matrix
    If all diagonal elements are zeros, then return None
    :param matrix: array,
    :return: product value or None
    """
    diag = np.diag(matrix)
    nonzero_diag = diag[diag > 0]
    if nonzero_diag.size == 0:
        return None
    return diag[diag > 0].prod()

In [114]:
A = np.random.normal(2, 4, (3, 4))
A

array([[ 5.97353067,  1.93997272,  1.67749668, -1.29113379],
       [-4.0039145 ,  3.67314016,  3.35010369, -2.43998486],
       [ 3.09972675,  3.42472   ,  1.68171891,  1.74381176]])

In [115]:
np.diag(A)

array([5.97353067, 3.67314016, 1.68171891])

In [122]:
nonzero_product(A)

36.89962954880613

In [118]:
B = np.array([[1, 2], [3, 0]])
B

array([[1, 2],
       [3, 0]])

In [123]:
nonzero_product(B)

1

In [120]:
C = np.array([[0, 2], [3, 0]])
C

array([[0, 2],
       [3, 0]])

In [128]:
print(nonzero_product(C))

None


## Titanic

In [130]:
df = pd.read_csv('titanic.csv', sep='\t')
df.shape

(156, 12)

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  156 non-null    int64  
 1   Survived     156 non-null    int64  
 2   Pclass       156 non-null    int64  
 3   Name         156 non-null    object 
 4   Sex          156 non-null    object 
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64  
 7   Parch        156 non-null    int64  
 8   Ticket       156 non-null    object 
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     object 
 11  Embarked     155 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB


In [144]:
df.columns[df.isna().any()]

Index(['Age', 'Cabin', 'Embarked'], dtype='object')

In [142]:
df.isna().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [131]:
df.head(11)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S

In [161]:
counts = df.groupby('Pclass')['Pclass'].count()
counts

Pclass
1    30
2    30
3    96
Name: Pclass, dtype: int64

In [162]:
counts / df.shape[0]

Pclass
1    0.192308
2    0.192308
3    0.615385
Name: Pclass, dtype: float64

In [148]:
df['Family'] = df.apply(lambda row: row['Name'].split(",")[0], axis=1)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked     Family  
0      0         A/5 21171   7.2500   NaN        S     Braund  
1      0          PC 17599  71.2833   C85        C    Cumings  
2      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen  
3      0            113803  53.1000  C123        S   Futrelle  
4      0            373450   8.0500   NaN        S      Allen

In [155]:
(df['Family'].value_counts() > 0).sum()

141

In [146]:
s = "Braund, Mr. Owen Harris"
s.split(",")[0]

'Braund'

In [139]:
df[(df['Sex'] == 'male') & (df['Survived'] == 1) & (df['Embarked'] == 'S') & (df['Fare'] > 30)]["Age"].mean()

30.0

In [156]:
def male_age(df: pd.DataFrame) -> float:
    """
    Return mean age of survived men, embarked in Southampton with fare > 30
    :param df: dataframe
    :return: mean age
    """
    return df[(df['Sex'] == 'male') & (df['Survived'] == 1) & (df['Embarked'] == 'S') & 
           (df['Fare'] > 30)]["Age"].mean()

def nan_columns(df: pd.DataFrame) -> tp.Iterable[str]:
    """
    Return list of columns containing nans
    :param df: dataframe
    :return: series of columns
    """
    return df.columns[df.isna().any()].tolist()
    

def class_distribution(df: pd.DataFrame) -> pd.Series:
    """
    Return Pclass distrubution
    :param df: dataframe
    :return: series with ratios
    """
    counts = df.groupby('Pclass')['Pclass'].count()
    counts.index.name = None
    return counts / df.shape[0]
    
def families_count(df: pd.DataFrame, k: int) -> int:
    """
    Compute number of families with more than k members
    :param df: dataframe,
    :param k: number of members,
    :return: number of families
    """
    df['Family'] = df.apply(lambda row: row['Name'].split(",")[0], axis=1)
    return (df['Family'].value_counts() > k).sum()

def mean_price(df: pd.DataFrame, tickets: tp.Iterable[str]) -> float:
    """
    Return mean price for specific tickets list
    :param df: dataframe,
    :param tickets: list of tickets,
    :return: mean fare for this tickets
    """

NameError: name 'tp' is not defined